#!/usr/bin/env python3
"""Build a minimal x86_64 PE32+ .exe for the H3OS PE ABI and emit a C header."""
from __future__ import annotations
import struct
import pathlib

# Machine code (SysV): rdi = api*
#   push rbp
#   mov rbp, rsp
#   push rbx
#   mov rbx, rdi
#   mov rax, [rbx+8]      ; write
#   lea rdi, [rip+msg]
#   call rax
#   mov rax, [rbx+16]     ; writeln
#   lea rdi, [rip+msg2]
#   call rax
#   xor eax, eax
#   pop rbx
#   pop rbp
#   ret

def build_code(msg: bytes, msg2: bytes) -> bytes:
    # We'll layout: code | msg | msg2
    # Use placeholders patched with rel32
    code = bytearray()
    code += b"\x55"                      # push rbp
    code += b"\x48\x89\xE5"              # mov rbp, rsp
    code += b"\x53"                      # push rbx
    code += b"\x48\x89\xFB"              # mov rbx, rdi
    code += b"\x48\x8B\x43\x08"          # mov rax, [rbx+8]  write
    # lea rdi, [rip+disp32]
    code += b"\x48\x8D\x3D"              # lea rdi, [rip+..]
    lea1 = len(code)
    code += b"\x00\x00\x00\x00"
    code += b"\xFF\xD0"                  # call rax
    code += b"\x48\x8B\x43\x10"          # mov rax, [rbx+16] writeln
    code += b"\x48\x8D\x3D"
    lea2 = len(code)
    code += b"\x00\x00\x00\x00"
    code += b"\xFF\xD0"                  # call rax
    code += b"\x31\xC0"                  # xor eax,eax
    code += b"\x5B"                      # pop rbx
    code += b"\x5D"                      # pop rbp
    code += b"\xC3"                      # ret

    msg_off = len(code)
    code += msg + b"\x00"
    msg2_off = len(code)
    code += msg2 + b"\x00"

    # rip-relative: disp = target - (insn_end)
    # lea is 7 bytes: 48 8D 3D disp32 — disp at lea1, insn ends at lea1+4
    def patch_lea(disp_at: int, target: int):
        insn_end = disp_at + 4
        rel = target - insn_end
        struct.pack_into("<i", code, disp_at, rel)

    patch_lea(lea1, msg_off)
    patch_lea(lea2, msg2_off)
    return bytes(code)


def align_up(v: int, a: int) -> int:
    return (v + a - 1) & ~(a - 1)


def build_pe(code: bytes) -> bytes:
    file_align = 0x200
    sect_align = 0x1000
    image_base = 0x140000000

    # DOS stub
    dos = bytearray(64)
    dos[0:2] = b"MZ"
    struct.pack_into("<I", dos, 0x3C, 0x80)  # e_lfanew

    stub = bytearray(0x80)
    stub[0:64] = dos
    # PE at 0x80
    pe_offset = 0x80

    # COFF + optional + section
    num_sections = 1
    opt_size = 0xF0  # PE32+ standard with 16 data dirs

    coff = struct.pack(
        "<IHHIIIHH",
        0x00004550,          # PE\0\0
        0x8664,              # AMD64
        num_sections,
        0,                   # timestamp
        0, 0,                # symbols
        opt_size,
        0x22,                # EXECUTABLE_IMAGE | LARGE_ADDRESS_AWARE
    )

    size_of_code = align_up(len(code), file_align)
    size_of_image = align_up(0x1000 + size_of_code, sect_align)
    size_of_headers = align_up(pe_offset + 4 + 20 + opt_size + 40, file_align)
    # coff struct above already includes signature (4) + 20 = 24... 
    # PE signature is 4 bytes, COFF is 20, we packed signature into coff as I = 24 bytes total for sig+coff

    entry_rva = 0x1000

    optional = bytearray(opt_size)
    struct.pack_into("<HBB", optional, 0, 0x20B, 14, 0)  # magic PE32+, linker
    struct.pack_into("<III", optional, 4, size_of_code, 0, 0)
    struct.pack_into("<II", optional, 16, entry_rva, 0x1000)  # entry, base of code
    struct.pack_into("<Q", optional, 24, image_base)
    struct.pack_into("<II", optional, 32, sect_align, file_align)
    struct.pack_into("<HHHHHH", optional, 40, 6, 0, 0, 1, 3, 0)  # versions / subsystem console=3
    struct.pack_into("<I", optional, 52, 0)  # win32version
    struct.pack_into("<II", optional, 56, size_of_image, size_of_headers)
    struct.pack_into("<IH", optional, 64, 0, 3)  # checksum, subsystem
    struct.pack_into("<H", optional, 68, 0)  # dll chars
    struct.pack_into("<QQQQ", optional, 70, 0x100000, 0x1000, 0x100000, 0x1000)
    struct.pack_into("<II", optional, 102, 0, 16)  # loader flags, #dirs
    # data directories zeroed

    # Section .text
    name = b".text\0\0\0"
    virt_size = len(code)
    virt_addr = 0x1000
    raw_size = size_of_code
    raw_ptr = size_of_headers
    chars = 0x60000020  # CODE | EXECUTE | READ
    section = name + struct.pack("<IIIIIIHHI", virt_size, virt_addr, raw_size, raw_ptr, 0, 0, 0, 0, chars)

    headers = bytearray(size_of_headers)
    headers[0:len(stub)] = stub
    pe_blob = coff + optional + section
    headers[pe_offset:pe_offset + len(pe_blob)] = pe_blob

    raw = bytearray(raw_ptr + raw_size)
    raw[0:len(headers)] = headers
    raw[raw_ptr:raw_ptr + len(code)] = code
    return bytes(raw)


def emit_header(pe: bytes, out: pathlib.Path, symbol: str = "hello_exe"):
    lines = [
        "/* Auto-generated by tools/mkpe.py — H3OS sample PE */",
        "#pragma once",
        "#include <h3os/types.h>",
        f"static const u8 {symbol}[] = {{",
    ]
    for i in range(0, len(pe), 12):
        chunk = pe[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"static const u32 {symbol}_len = {len(pe)};")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    root = pathlib.Path(__file__).resolve().parents[1]
    code = build_code(b"Hello from hello.exe on H3OS!", b"PE32+ loader works.")
    pe = build_pe(code)
    bin_path = root / "sdk" / "samples" / "hello.exe"
    bin_path.parent.mkdir(parents=True, exist_ok=True)
    bin_path.write_bytes(pe)
    hdr = root / "sdk" / "samples" / "hello_exe.h"
    emit_header(pe, hdr)
    print(f"Wrote {bin_path} ({len(pe)} bytes)")
    print(f"Wrote {hdr}")


if __name__ == "__main__":
    main()
